global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "prometheus-state-metrics"
    static_configs:
      - targets: ["192.168.99.105:32280"]
  - job_name: "node-exporter"
    static_configs:
      - targets: [ "192.168.99.105:9100" ]